(define (domain hospitaldomain)
  (:requirements :fluents :negative-preconditions :typing )
  (:types bed patient specialty care )
  
  (:predicates     
    (bedcare ?varbed - bed ?varcare - care)
    (bedmedicinainterna ?varbed - bed)
    (bedspecialty ?varbed - bed ?varspecialty - specialty)  
    (bedfree ?varbed - bed)
    (busybed ?varbed - bed)
    (in ?p - patient ?varbed - bed)
    (allocated ?p - patient)
    (patientcare ?p - patient ?varcare - care)
    (patientspecialty ?p - patient ?varspecialty - specialty)
    (patientmedicinainterna ?p - patient)
  )

  (:functions (age ?p - patient))

  (:action allocatemedicinainterna
    :parameters (?p - patient ?varbed - bed ?varcare - care )
    :precondition (and (not (allocated ?p)) 
                       (bedfree ?varbed) 
                       (bedmedicinainterna ?varbed) 
                       (bedcare ?varbed ?varcare)
                       (patientcare ?p ?varcare)
                       (patientmedicinainterna ?p)
                       )
    :effect (and (in ?p ?varbed) (allocated ?p) 
                 (busybed ?varbed))
  )
)
